### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ealmasque** [LazoCoder/Tic-Tac-Toe#2]
Hi @LazoCoder! 
This is not really an issue, but we wanted to let you know that we've used part of your AlphaBetaAdvanced.java in a hackathon last weekend.
Thanks for publishing your algo. under GPL3.0. It really helped us build a kick-ass robot that play tictactoe on a whiteboard 😊

In case you're interested, we've given you full credit for the AI and we wanted to share our gratitude with you:
https://gitlab.fabcloud.org/eduard.almasque/tic-tac-dog

Hugs from Barcelona

**Comment by LazoVelko** [comment]
@ealmasque That's very cool. I'm glad I could help. Thanks for sharing!
